# Generated by Django 5.2.9 on 2026-01-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
