# Generated by Django 5.2.9 on 2026-01-01 17:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextData',
            fields=[
                ('context_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift', models.CharField(choices=[('day', 'Day (07:00 - 15:00)'), ('evening', 'Evening (15:00 - 23:00)'), ('night', 'Night (23:00 - 07:00)')], default='day', max_length=50)),
                ('staffing_level', models.CharField(choices=[('low', 'Low Staffing'), ('medium', 'Normal Staffing'), ('high', 'Full Staffing')], default='medium', max_length=50)),
                ('er_capacity_level', models.CharField(choices=[('under', 'Under Capacity'), ('at', 'At Capacity'), ('over', 'Over Capacity')], default='at', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('er_section', models.CharField(choices=[('Main', 'Main ER'), ('FastTrack', 'Fast Track'), ('Trauma', 'Trauma Bay'), ('Peds', 'Pediatrics')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'er_section'], name='patients_co_date_bc4d3f_idx')],
                'unique_together': {('date', 'shift', 'er_section')},
            },
        ),
        migrations.CreateModel(
            name='ERVisits',
            fields=[
                ('visit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arrival_ts', models.DateTimeField()),
                ('triage_ts', models.DateTimeField(blank=True, null=True)),
                ('first_contact_ts', models.DateTimeField(blank=True, null=True)),
                ('disposition_ts', models.DateTimeField(blank=True, null=True)),
                ('triage_level', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('er_section', models.CharField(choices=[('Main', 'Main ER'), ('FastTrack', 'Fast Track'), ('Trauma', 'Trauma Bay'), ('Peds', 'Pediatrics')], max_length=50)),
                ('disposition_type', models.CharField(blank=True, choices=[('Admitted', 'Admitted to Hospital'), ('Discharged', 'Discharged Home'), ('LWBS', 'Left Without Being Seen'), ('Transferred', 'Transferred to Other Facility')], max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='er_visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('initial', 'Initial Contact'), ('delay_update', 'Delay/Wait Time Update'), ('clinical_update', 'Clinical/Results Update'), ('disposition_plan', 'Disposition/Discharge Plan'), ('other', 'Other')], default='initial', max_length=50)),
                ('event_ts', models.DateTimeField(auto_now_add=True)),
                ('staff_role', models.CharField(choices=[('nurse', 'Nurse'), ('physician', 'Physician'), ('admin', 'Admin')], max_length=20)),
                ('initiated_by', models.CharField(choices=[('staff', 'Staff Proactive'), ('patient', 'Patient/Family Request')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='patients.ervisits')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceFailureIndicator',
            fields=[
                ('indicator_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lwbs', models.BooleanField(default=False)),
                ('revisit_reason', models.CharField(blank=True, choices=[('worsening', 'Symptoms Worsened'), ('new_issue', 'New Unrelated Issue'), ('planned', 'Planned Follow-up')], max_length=50, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='failure_report', to='patients.ervisits')),
            ],
        ),
        migrations.CreateModel(
            name='SatisfactionSignal',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('waiting_score', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('communication_score', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('respect_score', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='patients.ervisits')),
            ],
        ),
        migrations.AddIndex(
            model_name='ervisits',
            index=models.Index(fields=['er_section', 'triage_level'], name='patients_er_er_sect_a44146_idx'),
        ),
        migrations.AddIndex(
            model_name='ervisits',
            index=models.Index(fields=['disposition_type'], name='patients_er_disposi_e9b7ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ervisits',
            unique_together={('patient', 'arrival_ts')},
        ),
        migrations.AddIndex(
            model_name='communicationevent',
            index=models.Index(fields=['visit', 'event_ts'], name='patients_co_visit_i_0a1505_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationevent',
            index=models.Index(fields=['event_type'], name='patients_co_event_t_e6a6ed_idx'),
        ),
        migrations.AddIndex(
            model_name='experiencefailureindicator',
            index=models.Index(fields=['lwbs'], name='patients_ex_lwbs_1d9496_idx'),
        ),
        migrations.AddIndex(
            model_name='satisfactionsignal',
            index=models.Index(fields=['overall_score', 'waiting_score'], name='patients_sa_overall_db1b44_idx'),
        ),
    ]
