# Generated by Django 5.2.9 on 2026-01-01 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ERVisits',
            new_name='ERVisit',
        ),
        migrations.RenameIndex(
            model_name='ervisit',
            new_name='patients_er_er_sect_b393cb_idx',
            old_name='patients_er_er_sect_a44146_idx',
        ),
        migrations.RenameIndex(
            model_name='ervisit',
            new_name='patients_er_disposi_036780_idx',
            old_name='patients_er_disposi_e9b7ca_idx',
        ),
        migrations.AddField(
            model_name='experiencefailureindicator',
            name='time_to_first_contact',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
