# Generated by Django 5.2.9 on 2026-01-04 02:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_rename_ervisits_ervisit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ervisit',
            name='age_group',
            field=models.CharField(blank=True, choices=[('child', 'Child (0-12)'), ('teen', 'Teen (13-17)'), ('young_adult', 'Young Adult (18-34)'), ('adult', 'Adult (35-64)'), ('senior', 'Senior (65+)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ervisit',
            name='length_of_stay',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ervisit',
            name='revisit_72h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experiencefailureindicator',
            name='comm_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='failure_indicator', to='patients.communicationevent'),
        ),
        migrations.AddField(
            model_name='experiencefailureindicator',
            name='time_without_communication',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='communicationevent',
            name='event_type',
            field=models.CharField(choices=[('initial', 'Initial Contact'), ('delay_update', 'Delay/Wait Time Update'), ('clinical_update', 'Clinical/Results Update'), ('other', 'Other')], default='initial', max_length=50),
        ),
        migrations.AlterField(
            model_name='ervisit',
            name='arrival_ts',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ervisit',
            name='disposition_type',
            field=models.CharField(blank=True, choices=[('admitted', 'Admitted to Hospital'), ('discharged', 'Discharged Home'), ('lwbs', 'Left Without Being Seen'), ('transferred', 'Transferred to Other Facility')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ervisit',
            name='er_section',
            field=models.CharField(choices=[('main', 'Main ER'), ('fasttrack', 'Fast Track'), ('trauma', 'Trauma Bay'), ('peds', 'Pediatrics')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ervisit',
            name='triage_level',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='experiencefailureindicator',
            name='time_to_first_contact',
            field=models.DurationField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='satisfactionsignal',
            name='communication_score',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='satisfactionsignal',
            name='overall_score',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='satisfactionsignal',
            name='respect_score',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='satisfactionsignal',
            name='waiting_score',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='experiencefailureindicator',
            index=models.Index(fields=['time_to_first_contact'], name='patients_ex_time_to_3b4dcb_idx'),
        ),
    ]
